#!/bin/bash
#
# Documentation of tools/print_config.py
# https://mmsegmentation.readthedocs.io/en/latest/useful_tools.html#print-the-entire-config

python /mmsegmentation/tools/misc/print_config.py "$@"
